Update image_data.py
needs to be converted to `str`, otherwise if is determined from data, it will fail with:
```
image_data.py", line 26, in _get_default_contrast_limits
    dtype = "u" + dtype
TypeError: can only concatenate str (not "numpy.dtype[int8]") to str
```